apiVersion: v1
kind: ConfigMap
metadata:
  name: post-init-scripts
  namespace: ___NAMESPACE___
  labels:
    application: patroni-___CLUSTERNAME____-db
    cluster-name: ___CLUSTERNAME____
    app: ___CLUSTERNAME____
data:
  001.sql: |
    ___USER_AND_DATABASE_CREATE_SCRIPT___
---
apiVersion: v1
kind: Secret
metadata:
  name: ___CLUSTERNAME____-db
  namespace: ___NAMESPACE___
  labels:
    application: patroni-___CLUSTERNAME____-db
    cluster-name: ___CLUSTERNAME____-db
    app: ___CLUSTERNAME____
type: Opaque
data:
  superuser-password: ___AUTOCREATED___
  replication-password: ___AUTOCREATED___
---
apiVersion: v1
kind: Service
metadata:
  name: ___CLUSTERNAME____-db-config
  namespace: ___NAMESPACE___
  labels:
    application: patroni-___CLUSTERNAME____-db
    cluster-name: ___CLUSTERNAME____-db
    app: ___CLUSTERNAME____
spec:
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: ___CLUSTERNAME____-db
  namespace: ___NAMESPACE___
  labels:
    application: patroni-___CLUSTERNAME____-db
    cluster-name: ___CLUSTERNAME____-db
    app: ___CLUSTERNAME____
spec:
  type: ClusterIP
  selector:
    application: patroni-___CLUSTERNAME____-db
    cluster-name: ___CLUSTERNAME____-db
    app: ___CLUSTERNAME____
    role: primary
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: ___CLUSTERNAME____-db-repl
  namespace: ___NAMESPACE___
  labels:
    application: patroni-___CLUSTERNAME____-db
    cluster-name: ___CLUSTERNAME____-db
    app: ___CLUSTERNAME____
spec:
  type: ClusterIP
  selector:
    application: patroni-___CLUSTERNAME____-db
    cluster-name: ___CLUSTERNAME____-db
    app: ___CLUSTERNAME____
    role: replica
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ___CLUSTERNAME____-db
  namespace: ___NAMESPACE___
  labels:
    application: patroni-___CLUSTERNAME____-db
    cluster-name: ___CLUSTERNAME____-db
    app: ___CLUSTERNAME____
spec:
  selector:
    matchLabels:
      application: patroni-___CLUSTERNAME____-db
      cluster-name: ___CLUSTERNAME____-db
      app: ___CLUSTERNAME____
  replicas: ___REPLICA_COUNT___ 
  serviceName: ___CLUSTERNAME____-db
  template:
    metadata:
      labels:
        application: patroni-___CLUSTERNAME____-db
        cluster-name: ___CLUSTERNAME____-db
        app: ___CLUSTERNAME____
    spec:
      serviceAccountName: ___SANAME___
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "cluster-name"
                    operator: In
                    values:
                    - ___CLUSTERNAME____-db
              topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: chown-pgdata
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - chown
        - -R
        - "999:999"
        - "/home/postgres/pgdata"
        volumeMounts:
        - mountPath: /home/postgres/pgdata
          name: pgdata
      containers:
      - name: ___CLUSTERNAME____-db
        image: ___IMAGE___
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readiness
            port: 8008
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /home/postgres/pgdata
          name: pgdata
        - name: walgbackup
          mountPath: /walg
        - mountPath: /home/postgres/post-init.d
          name: post-init-scripts
        env:
        - name: HOME
          value: /home/postgres
        - name: PATRONI_KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PATRONI_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PATRONI_KUBERNETES_BYPASS_API_SERVICE
          value: 'false'
        - name: PATRONI_KUBERNETES_USE_ENDPOINTS
          value: 'true'
        - name: PATRONI_KUBERNETES_LABELS
          value: '{application: patroni-___CLUSTERNAME____-db, cluster-name: ___CLUSTERNAME____-db, app: ___CLUSTERNAME____}'
        - name: PATRONI_SUPERUSER_USERNAME
          value: postgres
        - name: PATRONI_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ___CLUSTERNAME____-db
              key: superuser-password
        - name: PATRONI_REPLICATION_USERNAME
          value: standby
        - name: PATRONI_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ___CLUSTERNAME____-db
              key: replication-password
        - name: PATRONI_SCOPE
          value: ___CLUSTERNAME____-db
        - name: PATRONI_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PATRONI_POSTGRESQL_DATA_DIR
          value: /home/postgres/pgdata/pgroot/data
        - name: PATRONI_POSTGRESQL_PGPASS
          value: /tmp/pgpass
        - name: PATRONI_POSTGRESQL_LISTEN
          value: '0.0.0.0:5432'
        - name: PATRONI_RESTAPI_LISTEN
          value: '0.0.0.0:8008'
        - name: WALG_BACKUP_CONFIG
          value: "/walg/config.json"
        - name: WALG_S3_PREFIX
          value: "___S3_BUCKET_ADDRESS___" 
        - name: DB_ARCHIVE_MODE
          value: "___ARCHIVE_MODE___"
      terminationGracePeriodSeconds: 0
      volumes:
      - name: walgbackup
        configMap:
          name: walgbackup
          defaultMode: 0444
          items:
          - key: config.json
            path: config.json
      - name: post-init-scripts
        configMap:
          name: post-init-scripts
          defaultMode: 0444
  volumeClaimTemplates:
  - metadata:
     labels:
       application: patroni-___CLUSTERNAME____-db
       cluster-name: ___CLUSTERNAME____-db
     name: pgdata
    spec:
     storageClassName: ___STORAGE_CLASS_NAME___
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 5Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-___CLUSTERNAME____-db
  namespace: ___NAMESPACE___
  labels:
    application: patroni-___CLUSTERNAME____-db
    cluster-name: ___CLUSTERNAME____-db
    app: ___CLUSTERNAME____
spec:
  schedule: "45 00 * * *"
  suspend: ___SUSPEND___
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ___SANAME___
          restartPolicy: Never
          containers:
          - name: backup-___CLUSTERNAME____-db
            command:
            - /walg/backup.sh
            image: bitnami/kubectl:1.31
            imagePullPolicy: IfNotPresent
            env:
            - name: DB_CLUSTER
              value: ___CLUSTERNAME____-db
            - name: WALG_CONFIG
              value: /walg/config.json
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            volumeMounts:
            - name: walgbackup
              mountPath: /walg
          volumes:
          - name: walgbackup
            configMap:
              name: walgbackup
              defaultMode: 0755
              items:
              - key: backup.sh
                path: backup.sh

