---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ___SANAME___
  namespace: ___NAMESPACE___
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ___SANAME___
  namespace: ___NAMESPACE___
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - patch
  - update
  - list
  - watch
  - delete
  - deletecollection
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ___SANAME___
  namespace: ___NAMESPACE___
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ___SANAME___
subjects:
- kind: ServiceAccount
  name: ___SANAME___
  namespace: ___NAMESPACE___
